header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: cavlabs/jiguang-sdk-go authors.

  paths:
    - '**/*.go'

  paths-ignore:
    - 'third_party/**'
    - 'examples/**'

  comment: on-failure
